# You can change this base image to anything else
# But make sure to use the correct version of Java
FROM adoptopenjdk/openjdk11:alpine

# Simply the artifact path
ARG artifact=target/spring-boot-web.jar
ADD target/spring-boot-web.jar spring-boot-web.jar

WORKDIR /opt/app

COPY ${artifact} /opt/app/

# This should not be changed
ENTRYPOINT ["java","-jar","app.jar"]
